language: node_js
node_js:
  - "8"
sudo: required
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: out/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false
git:
  depth: 1
before_install:
- npm install -g lerna grunt-cli gatsby-cli
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn bootstrap
install: true
script:
- yarn prebuild
- yarn build
after_success: |
  cd "$TRAVIS_BUILD_DIR"
  # This generates a `web` directory containing the website.
  mkdir -p out/4.0
  cp -R $TRAVIS_BUILD_DIR/packages/patternfly-3/_site/. $TRAVIS_BUILD_DIR/out/
  cp -R $TRAVIS_BUILD_DIR/packages/patternfly-4/public/. $TRAVIS_BUILD_DIR/out/4.0/